# Generated by Django 5.1.6 on 2025-08-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
